#:kivy 1.1.0
<OpenDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserIconView:
            id: filechooser

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Annuler"
                on_release: root.cancel()

            Button:
                text: "Ouvrir"
                on_release: root.load(filechooser.path, filechooser.selection)