<IntervalPopup@Popup>:
    id : intervalpopup
    intervalbox:intervalbox
    title:""
    separator_height:0    
    auto_dismiss: False
    size_hint: (.7,.2)
    BoxLayout:
        orientation:"horizontal"
        IntervalBox:
            id:intervalbox
            size_hint:(.8,1)
        CustButton:
            size_hint:(.2,1)           
            text: "OK"
            on_press: root.dismiss()


<CustButton@Button>:
    font_size:.3*self.height    